spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  security:
    user:
      name: username
      password: password
      roles: ADMIN
logging:
  level:
    org:
      springframework:
        security: DEBUG