version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      minor-and-patch-dependencies:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      minor-and-patch-dependencies:
        update-types:
          - "minor"
          - "patch"
    target-branch: "spring-boot-2.x"
    ignore:
      - dependency-name: "org.springframework.boot"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
